require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  Exclude:
    - 'bin/**/*'
    - 'Rakefile'
    - 'spec/dummy/bin/**/*'
  TargetRubyVersion: 2.6

Bundler/GemComment:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/ClassMethodsDefinitions:
  EnforcedStyle: self_class

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  AllowedCops:
    - Metrics/BlockLength
    - Metrics/ParameterLists
    - Naming/AccessorMethodName

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  AllowParenthesesInCamelCaseMethod: true
  EnforcedStyle: omit_parentheses

Style/MissingElse:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent
